from fastapi import HTTPException
import pdfplumber
import io
#import LLM
from google.genai import types
import google.genai as genai
from groq import Groq
from openai import OpenAI
import pytesseract


import os
from dotenv import load_dotenv


#object
load_dotenv()


#llm connections
genai_client=genai.Client(api_key=os.getenv("GOOGLE_API_KEY"))
groq_client = Groq(api_key=os.getenv("GROQ_API_KEY"))
openrouter_client = OpenAI(
  base_url="https://openrouter.ai/api/v1",
  api_key=os.getenv("openrouter_api")
)

def ask_llm(prompt):
     try:
            response=genai_client.models.generate_content(model="gemini-3.5-flash",contents=prompt)

            response_text=response.text
            if response_text:
               return response_text
            else:
                 raise("The response is not generated by gemini")
            
     except Exception as e:
          print(f"Gemini error:{str(e)}")
          try:
              #groq model
              response_ = groq_client.chat.completions.create(messages=[
              {
                "role": "user",
                 "content":prompt
              }],
                 model="llama-3.3-70b-versatile")
              
              if response_:
                 return response_.choices[0].message.content
              else:
                 raise("The response is not generated by groq llm")
              
          except Exception as e:
              print(f"Groq error:{str(e)}")
              #print("length of prompt:",len(prompt))
              #openrouter
              model1="~openai/gpt-latest"
              completion = openrouter_client.chat.completions.create(model="nvidia/nemotron-3-super-120b-a12b",
                        messages=[
                  {
                    "role": "user",
                    "content":prompt
                  }
                      ]
                        ) 
              if completion:
                 return completion.choices[0].message.content
              else:
                 raise("The response is not generated by llm")


async def extract_text_from_pdf(file):
   #for text based pdf's
   try:
    if file.content_type != "application/pdf":
        raise ValueError("Invalid file type. Please upload a PDF file.")

    pdf_bytes = file.file.read()
    extracted_text=""

    with pdfplumber.open(io.BytesIO(pdf_bytes)) as pdf:
        for page in pdf.pages:
            page_img=page.to_image(resolution=200).original
            text=pytesseract.image_to_string(page_img)

            if text:
                extracted_text+=text+"\n"
                #print(f"inside extract_text_from_pdf:{extracted_text}")
                return extracted_text 
            else:
                 return {"message":"Provided Pdf may be Empty.please upload a valid pdf."}   

        
   except Exception as e:
        print("Error in Extracting data through OCR engine")
              #using llm model
        try:
            if pdf.content_type != "application/pdf":
                        raise ValueError("Invalid file type. Please upload a PDF file.")  
            pdf_bytes = pdf.file.read()
            response = genai_client.models.generate_content(
            model="gemini-2.5-flash",
            contents=[
            types.Part.from_text(text="please perform OCR on this scanned PDF." \
            "Extract text from given pdf exactly as it appears, preserving formating were possible"),
            types.Part.from_bytes(data=pdf_bytes,mime_type="application/pdf")
            ]
        )
            response_text=response.text
            if response_text:
                print(f"Text Extracted from {pdf.filename}")
                return response_text
            else:
                raise HTTPException(status_code=500,detail="The response is not generated by gemini")
        except Exception as e:
            raise HTTPException(status_code=500,detail=f"Error in model gemini-2.5-flash error:{str(e)}")