from fastapi import HTTPException
from dotenv import load_dotenv
from service.resume_analysis import extracted_res_data
from service.core_services import ask_llm

load_dotenv()


def frequently_asked_questions(level:str,user,db):
    resume_data=extracted_res_data(db,user)
    prompt=f"""context: I am a student completed {user.Highest_Class} class. I am actively applying for job/intenships.
    role: act as a Experienced recruiter.
    action: Based on difficulty level and career goal generate top 10 most frequently asked questions in interview.
    along with that also provide highly acceptable personalised answers from resume data. if the resume data is not provided
    then generate generalised answers for questions.
    Difficulty Levels:
    Easy:
    Focuses on fundamental concepts and basic questions.
    Medium:
    Focuses on practical knowledge, application-based questions, and moderate technical depth.
    Hard:
    Focuses on complex concepts, problem-solving, system design, and deeper technical understanding. 
    
    format: return the response in structured list of dictionary format -> 
    [{{Q:your question1,
    A: your answer for Q1}},
    {{Q:your question2,
    A: your answer for Q2}},
    {{Q:your question3,
    A: your answer for Q3}},
    ..
    etc
     ]
    
    difficulty level={level},career_goal={user.Career_goal},resume_data={resume_data}

    Dont hallucinate.
    dont ask any follow up questions.
    """

    try:
        response=ask_llm(prompt)
        return response
    except Exception as e:
       raise HTTPException(status_code=500,detail=f"Response is not generated by an LLM. Error:{str(e)}")

