import pdfplumber
#import pytesseract # for image_based pdf parsing
from fastapi import HTTPException
import io
#import LLM
import google.genai as genai
from groq import Groq
from openai import OpenAI

import os
from dotenv import load_dotenv
import json
from database.schemas import users_resume

#object
load_dotenv()


#llm connections
genai_client=genai.Client(api_key=os.getenv("GOOGLE_API_KEY"))
groq_client = Groq(api_key=os.getenv("GROQ_API_KEY"))
openrouter_client = OpenAI(
  base_url="https://openrouter.ai/api/v1",
  api_key=os.getenv("openrouter_api")
)

def ask_llm(prompt):
     try:
            response=genai_client.models.generate_content(model="gemini-3.5-flash",contents=prompt)

            response_text=response.text
            if response_text:
               return response_text
            else:
                 raise("The response is not generated by gemini")
            
     except Exception as e:
          print(f"Gemini error:{str(e)}")
          try:
              #groq model
              response_ = groq_client.chat.completions.create(messages=[
              {
                "role": "user",
                 "content":prompt
              }],
                 model="llama-3.3-70b-versatile")
              
              if response_:
                 return response_.choices[0].message.content
              else:
                 raise("The response is not generated by groq llm")
              
          except Exception as e:
              print(f"Groq error:{str(e)}")
              #print("length of prompt:",len(prompt))
              #openrouter
              model1="~openai/gpt-latest"
              completion = openrouter_client.chat.completions.create(model="nvidia/nemotron-3-super-120b-a12b",
                        messages=[
                  {
                    "role": "user",
                    "content":prompt
                  }
                      ]
                        ) 
              if completion:
                 return completion.choices[0].message.content
              else:
                 raise("The response is not generated by llm")


async def extract_text_from_pdf(file):
   #for text based pdf's
   try:
    if file.content_type != "application/pdf":
        raise ValueError("Invalid file type. Please upload a PDF file.")

    pdf_bytes = file.file.read()
    extracted_text=""

    with pdfplumber.open(io.BytesIO(pdf_bytes)) as pdf:
        for page in pdf.pages:
            text=page.extract_text()

            if text:
                extracted_text+=text+"\n"
                #print(f"inside extract_text_from_pdf:{extracted_text}")
                #return extracted_text   

        information=await extract_info_from_text(resume_text=extracted_text) 
        info=information.strip()

        if info.startswith("```json") or info.endswith('```'):
                lines=info.split('\n')
                op=lines[1:-1]
        
                return json.dumps(op) 
        return info  #["Information"]
   except Exception as e:
       raise HTTPException(status_code=500,detail=f"Error:{str(e)}") 
   """try:
        import easyocr
        import fitz  # PyMuPDF (pure python installation)

        # 1. Initialize the EasyOCR reader (specifying English 'en')
        # It will download the model automatically without any system-level installers
        reader = easyocr.Reader(['en'])

        # 2. Open the PDF file using PyMuPDF
        doc = fitz.open(file.file)

        for page_num in range(len(doc)):
            page = doc.load_page(page_num)
            
            # Render the page to a pixmap (image pixels)
            pix = page.get_pixmap()
            image_bytes = pix.tobytes("png")
            
            # 3. Read the text directly from the image bytes
            result = reader.readtext(image_bytes, detail=0)
            
            print(f"--- Page {page_num + 1} Text ---")
            print(" ".join(result))
   except Exception as e:
       raise HTTPException(status_code=500,detail=f"Error in extractiong text from image-based pdf.->{str(e)}")"""           


async def extract_info_from_text(resume_text:str):
    prompt=f"""Extract the following information from the  provided resume text. 
    do not ask any follow up questions.
    Resume Text:{resume_text}
    response format should be strictly json like 
    {{
    "Name":extracted_name,
    "Contact Information":{{"Email":extracted_email,
                            "Phone Number":extracted_emailextracted_phone no}},
    "Summary or Objective" :Summary or Objective ,
    "Work Experience":{{Company Name, Job Title, Duration, Responsibilities}} ,
    "Education":{{Degree, Institution, Graduation Year}} ,
    "skills":[],
    "Certifications" :[],
    "Projects":[]  ,
    "languages":[],
    "Any other relevant information" :information                
    }}
    """
                       
    try:
      response=ask_llm(prompt)
      return response
    except Exception as e:
            raise HTTPException(status_code=404, detail=f"Error in generating response:{e}")                     
            
        
async def generate_resume_report(extracted_info,job_type):
    #openai models

    prompt=f"""context: I am a student, I am searching for jobs and internships. i want detailed analysis of my resume.
    role: act as a senior report generator. You are expert report generator.
    action: Based on the extracted information from the resume and the job type, generate a comprehensive report that includes:\n\n
    response format should same as
      {{
        Summary:your answer(string),\n
        ATS_Score:score(in percentage),\n
        Strengths:[your answer],\n
        Weaknesses:[your answer],\n
        Missing_skills:[your answer],\n
        Recommendations:your answer
        }}
        summary of the candidate's qualifications and suitability for the specified job type. in 1 to 2 sentance.
       strength and  weaknesses(of the candidate in relation to the job requirements.) \n
       Recommendations for improving the resume to better align with the job type.\n
       

    if the resume data matches 40% or above with job type then provide detailed summary. else
      just answer in a simple way like your resume is not applicable for this role, with the detailed reason of why not matches.\n\n 
    
    do not hallucinate and dont ask any follow up questions.  
    Extracted Information:{extracted_info}\n Job Type:{job_type}\n\n
    """

    try:
      response=ask_llm(prompt)
      return response
    except Exception as e:
            raise HTTPException(status_code=404, detail=f"Error in generating response:{e}") 
    
def resume_report(db,user): #get from database
    user_file=db.query(users_resume).filter(users_resume.Username==user.Username).first()
    if user_file:
        if user_file.Resume_report:
            return user_file.Resume_report
        else:
            return None
    else:
        raise HTTPException(status_code=500,detail="Error in fetching users_file_info")
    
def extracted_res_data(db,user):  # get from database
    user_file=db.query(users_resume).filter(users_resume.Username==user.Username).first()
    if user_file:
        if user_file.Extracted_text:
            return user_file.Extracted_text
        else:
            return None
    else:
        raise HTTPException(status_code=500,detail="Error in fetching users_file_info")
