from fastapi import HTTPException
from dotenv import load_dotenv
from service.service_resume_analysis import ask_llm,extracted_res_data

load_dotenv()


def frequently_asked_questions(level:str,user,db):
    resume_data=extracted_res_data(db,user)
    prompt=f"""context: I am a student completed {user.Highest_Class} class. I am actively applying for job/intenships.
    role: act as a Experienced recruiter.
    action: Based on difficulty level and career goal generate top 10 most frequently asked questions in interview.
    along with that also provide highly acceptable personalised answers from resume data. if the resume data is not provided
    then generate generalised answers for questions. 
    format: return the response in structured list of dictionary format -> 
    [{{Q1:your question1,
    A1: your answer for Q1}},
    {{Q2:your question2,
    A2: your answer for Q2}},
    {{Q3:your question3,
    A3: your answer for Q3}},
    ..
    etc
     ]
    
    difficulty level={level},career_goal={user.Career_goal},resume_data={resume_data}

    Dont hallucinate.
    dont ask any follow up questions.
    """

    try:
        response=ask_llm(prompt)
        return response
    except Exception as e:
       raise HTTPException(status_code=500,detail=f"Response is not generated by an LLM. Error:{str(e)}")

