import pdfplumber
from fastapi import HTTPException
import io
#import LLM
import google.genai as genai
from groq import Groq
from openai import OpenAI

import os
from dotenv import load_dotenv
import json
from database.schemas import users_resume

#object
load_dotenv()


#llm connections
genai_client=genai.Client(api_key=os.getenv("GOOGLE_API_KEY"))
groq_client = Groq(api_key=os.getenv("GROQ_API_KEY"))
openrouter_client = OpenAI(
  base_url="https://openrouter.ai/api/v1",
  api_key=os.getenv("openai_api_key"),
)

def ask_llm(prompt):
     try:
            response=genai_client.models.generate_content(model="gemini-3.5-flash",contents=prompt)
            '''data=response.to_json_dict()
            if data:
              return {"Information":data.get("candidates")[0].get("content").get("parts")[0]}
            else:
                 raise ValueError("Response not generated from gemini")'''
            
            response_text=response.text
            if response_text:
               return response_text
            else:
                 raise("The response is not generated by gemini")
            
     except:
          try:
              #groq model
              response_ = groq_client.chat.completions.create(messages=[
              {
                "role": "user",
                 "content":prompt
              }],
                 model="llama-3.3-70b-versatile")
              
              if response_text:
                 return response_.choices[0].message.content
              else:
                 raise("The response is not generated by groq llm")
              
          except:
              #openrouter
              completion = openrouter_client.chat.completions.create(model="~openai/gpt-latest",
                        messages=[
                  {
                    "role": "user",
                    "content":prompt
                  }
                      ]
                        ) 
              if response_text:
                 return completion.choices[0].message.content
              else:
                 raise("The response is not generated by llm")


async def extract_text_from_pdf(file):

    if file.content_type != "application/pdf":
        raise ValueError("Invalid file type. Please upload a PDF file.")

    pdf_bytes = file.file.read()
    extracted_text=""

    with pdfplumber.open(io.BytesIO(pdf_bytes)) as pdf:
        for page in pdf.pages:
            text=page.extract_text()

            if text:
                extracted_text+=text+"\n"

        information=await extract_info_from_text(extracted_text) 
        info=information.strip()
        op=[]
        if info.startswith("```json") or info.endswith('```'):
             lines=info.split('\n')
             op=lines[1:-1]
       
    return json.dumps(op)   #["Information"]        


async def extract_info_from_text(resume_text):
    
    prompt=f"""Extract the following information from the resume text:\n\n1. Name\n
    2. Contact Information (Email, Phone Number)\n3. Summary or Objective\n
    4. Work Experience (Company Name, Job Title, Duration, Responsibilities)\n
    5. Education (Degree, Institution, Graduation Year)\n6. Skills\n7. Certifications\n
    8. Projects\n9. Languages\n10. Any other relevant information\n\nResume Text:\n{resume_text}\n\n
    Please provide the extracted information in a structured  json format."""
                       
    try:
      response=ask_llm(prompt)
      return response
    except Exception as e:
            raise HTTPException(status_code=404, detail=f"Error in generating response:{e}")                     
            
        
async def generate_resume_report(extracted_info,job_type):
    model="gemini-3.5-flash"
     #openai models
    _model1="gpt-3.5-turbo"
    prompt=f"""Based on the extracted information from the resume and the job type, generate a comprehensive report that includes:\n\n
    1. A summary of the candidate's qualifications and suitability for the specified job type.\n
    2. Strengths and weaknesses of the candidate in relation to the job requirements.\n
    3. Recommendations for improving the resume to better align with the job type.\n
    4. Any potential red flags or concerns that employers might have based on the resume content.\n\n
    if the extracted information does not matches with the job type then do not create full structured report
      just answer in a simple way like your resume is not applicable for this role, with the detailed reason of why not matches. 
    Extracted Information:\n{extracted_info}\n\nJob Type:\n{job_type}\n\n
    """

    try:
      response=ask_llm(prompt)
      return response
    except Exception as e:
            raise HTTPException(status_code=404, detail=f"Error in generating response:{e}") 
    
def resume_report(db,user): #get from database
    user_file=db.query(users_resume).filter(users_resume.Username==user.Username).first()
    if user_file:
        if user_file.Resume_report:
            return user_file.Resume_report
        else:
            return None
    else:
        raise HTTPException(status_code=500,detail="Error in fetching users_file_info")
    
def extracted_res_data(db,user):  # get from database
    user_file=db.query(users_resume).filter(users_resume.Username==user.Username).first()
    if user_file:
        if user_file.Extracted_text:
            return user_file.Extracted_text
        else:
            return None
    else:
        raise HTTPException(status_code=500,detail="Error in fetching users_file_info")
