from fastapi import HTTPException
from dotenv import load_dotenv
from service.service_resume_analysis import ask_llm,extracted_res_data

load_dotenv()


def frequently_asked_questions(level:str,user,db):
    resume_data=extracted_res_data(db,user)
    prompt=f"""context: I am a student completed {user.Highest_Class} class. I am actively applying for job/intenships.
    role: act as a Experienced recruiter.
    action: Based on difficulty level and career goal generate top 10 most frequently asked questions in interview.
    along with that also provide highly acceptable personalised answers from resume data. if the resume data is not provided
    then generate generalised answers for questions. 
    format: return the response in structured json format -> {{
    question1:ans1,
    question2:ans2.
    etc...
    difficulty level={level},career_goal={user.Career_goal},resume_data={resume_data}

    Dont hallucinate.
    }}
    """

    try:
        response=ask_llm(prompt)
        return response
    except Exception as e:
       raise HTTPException(status_code=500,detail=f"Response is not generated by an LLM. Error:{str(e)}")

